### PR TITLE
adding sha384 to ALGOS table

### PR DESCRIPTION
**Pull request by zcaudate**
as title suggests.

### CODE REVIEW

**Comment by zcaudate** [comment]
thanks. would the luarocks package be updated?

**Comment by zcaudate** [comment]
sorry. I'm pretty new to lua so I don't know how the luarocks system works.

**Comment by jkeys089** [comment]
@zcaudate I published a new version this morning.

**Comment by zcaudate** [comment]
@jkeys089 awesome. thanks!

**Pull request merged**
